collections:
  posts:
    output: true
    permalink: /posts/:title/
    directory: "_posts"  
  


title: GeamiGeami Japanese
description: Japanese Page

url: "https://gaemigaemi.github.io/japanese" 

plugins:
  - jekyll-feed
  - jekyll-seo-tag