collections:
  elements:
    output: true
    permalink: /elements/:title/
    directory: "_elements"  
  


title: GeamiGeami Japanese
description: Japanese Page

url: "https://gaemigaemi.github.io/japanese" 

plugins:
  - jekyll-feed
  - jekyll-seo-tag